### ISSUE TITLE
please add new optional parameter for the 'transferBalance' method

### ISSUE THREAD

**Issue by ethene** [s4w3d0ff/python-poloniex#132]
>>> polo.transferBalance(currency='BTC', fromAccount='margin', toAccount='lending',amount=0.01661075)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/strky/anaconda3/envs/py36/lib/python3.6/site-packages/poloniex/__init__.py", line 525, in transferBalance
    'toAccount': str(toAccount)
  File "/home/strky/anaconda3/envs/py36/lib/python3.6/site-packages/poloniex/__init__.py", line 143, in retrying
    return func(*args, **kwargs)
  File "/home/strky/anaconda3/envs/py36/lib/python3.6/site-packages/poloniex/__init__.py", line 203, in __call__
    return self.handleReturned(ret.text)
  File "/home/strky/anaconda3/envs/py36/lib/python3.6/site-packages/poloniex/__init__.py", line 270, in handleReturned
    raise PoloniexError(out['error'])

poloniex.PoloniexError: Transferring 0.01661075 BTC from your margin account would bring your current margin to 92.03%, putting you in greater danger of a forced liquidation. Please confirm this action by passing confirmed=1 with your request.

as there is no 'confirmed' parameter, please add this one with an empty default value

**Comment by s4w3d0ff** [comment]
That should do it, I'm curious if there are more commands that can trigger this error...
