### ISSUE TITLE
urllib2.HTTPError: HTTP Error 422

### ISSUE THREAD

**Issue by crack00r** [s4w3d0ff/python-poloniex#153]
```
Unhandled exception in thread started by <class classes.PoloniexThread.PoloniexThread at 0x0000000004DDC2E8>
Traceback (most recent call last):
  File "C:\Users\MG\PycharmProjects\BitBot2\classes\PoloniexThread.py", line 19, in __init__
    self.balance = float( self.exchange.returnBalances()[coin] )
  File "C:\Users\MG\PycharmProjects\BitBot2\classes\Poloniex.py", line 75, in returnBalances
    return self.api_query('returnBalances')
  File "C:\Users\MG\PycharmProjects\BitBot2\classes\Poloniex.py", line 55, in api_query
    ret = urllib2.urlopen(urllib2.Request('https://poloniex.com/tradingApi', post_data, headers))
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 422:
Unhandled exception in thread started by <class classes.PoloniexThread.PoloniexThread at 0x0000000004DDC2E8>
Traceback (most recent call last):
  File "C:\Users\MG\PycharmProjects\BitBot2\classes\PoloniexThread.py", line 19, in __init__
    self.balance = float( self.exchange.returnBalances()[coin] )
  File "C:\Users\MG\PycharmProjects\BitBot2\classes\Poloniex.py", line 75, in returnBalances
    return self.api_query('returnBalances')
  File "C:\Users\MG\PycharmProjects\BitBot2\classes\Poloniex.py", line 55, in api_query
    ret = urllib2.urlopen(urllib2.Request('https://poloniex.com/tradingApi', post_data, headers))
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 422:
Unhandled exception in thread started by <class classes.PoloniexThread.PoloniexThread at 0x0000000004DDC2E8>
Traceback (most recent call last):
  File "C:\Users\MG\PycharmProjects\BitBot2\classes\PoloniexThread.py", line 19, in __init__
    self.balance = float( self.exchange.returnBalances()[coin] )
  File "C:\Users\MG\PycharmProjects\BitBot2\classes\Poloniex.py", line 75, in returnBalances
    return self.api_query('returnBalances')
  File "C:\Users\MG\PycharmProjects\BitBot2\classes\Poloniex.py", line 55, in api_query
    ret = urllib2.urlopen(urllib2.Request('https://poloniex.com/tradingApi', post_data, headers))
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 422:


```

**Comment by s4w3d0ff** [comment]
Seems like you aren't using this wrapper. This wrapper uses `requests` (which uses `urllib3`). Your traceback is showing `urllib2` (along with other functions that do not exist within this wrapper.)

It seems like your script is importing another poloniex wrapper locally: 
```
BitBot2\classes\PoloniexThread.py
```

**Comment by crack00r** [comment]
ok, its still this
https://pastebin.com/fbkheaRb
