### ISSUE TITLE
Poloniex always return 'captcha require', how to solve it?

### ISSUE THREAD

**Issue by kimkha** [s4w3d0ff/python-poloniex#35]
I just use the script, but it always issues error. When I change `return _loads(ret.text, parse_float=unicode)` to `ret.text` in function `__call__`, it prints out full HTML code of captcha page of poloniex.com. So, I cannot do anything.

How can we deal with that?

Please help.

----
This is the log for first time call (without any changes):

```>>> from poloniex import Poloniex
>>> polo = Poloniex()
>>> print(polo.returnTicker())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "poloniex/__init__.py", line 232, in returnTicker
    return self.__call__('returnTicker')
  File "poloniex/__init__.py", line 221, in __call__
    return _loads(ret.text, parse_float=unicode)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded```

**Comment by s4w3d0ff** [comment]
That is strange. I just tested on python 2.7

```
Python 2.7.12
[GCC 5.4.0 20160609] on linux2
>>> import poloniex
>>> polo = poloniex.Poloniex()
>>> polo.returnTicker()['BTC_ZEC']
{u'last': u'0.08900011', u'quoteVolume': u'15824.22964267', u'high24hr': u'0.09950000', u'isFrozen': u'0', u'highestBid': u'0.08900011', u'percentChange': u'0.12701164', u'low24hr': u'0.07336143', u'lowestAsk': u'0.08900497', u'id': 178, u'baseVolume': u'1338.37997487'}
>>> 
```
I also tried python 3:
```
Python 3.5.2
[GCC 5.4.0 20160609] on linux
>>> import poloniex
>>> polo = poloniex.Poloniex()
>>> polo.returnTicker()['BTC_ZEC']
{'quoteVolume': '15826.68738452', 'highestBid': '0.09001010', 'last': '0.09001010', 'percentChange': '0.14644248', 'id': 178, 'high24hr': '0.09950000', 'isFrozen': '0', 'low24hr': '0.07336143', 'baseVolume': '1339.36835406', 'lowestAsk': '0.09008964'}
>>> 
```

You could also turn on more verbose logging to try and see what is going on:
```
>>> import poloniex, logging

>>> polo = poloniex.Poloniex(loglevel=logging.INFO)
>>> polo.returnTicker()['BTC_ZEC']
[21:09:13] Starting new HTTPS connection (1): poloniex.com
{'quoteVolume': '16203.95492493', 'highestBid': '0.09314328', 'last': '0.09314328', 'percentChange': '0.17831277', 'id': 178, 'high24hr': '0.09950000', 'isFrozen': '0', 'low24hr': '0.07336143', 'baseVolume': '1376.16209850', 'lowestAsk': '0.09320000'}

>>> polo = poloniex.Poloniex(loglevel=logging.DEBUG)
>>> polo.returnTicker()['BTC_ZEC']
[21:09:34] Starting new HTTPS connection (1): poloniex.com
[21:09:34] "POST /public?command=returnTicker HTTP/1.1" 200 None
{'quoteVolume': '16221.56580348', 'highestBid': '0.09314329', 'last': '0.09314328', 'percentChange': '0.17310394', 'id': 178, 'high24hr': '0.09950000', 'isFrozen': '0', 'low24hr': '0.07336143', 'baseVolume': '1377.81006665', 'lowestAsk': '0.09320000'}
>>> 
```

It could be that the public commands are expected to be GET requests and the module uses POST (`requests.post()`) If this is the issue, you could try [this branch](https://github.com/s4w3d0ff/python-poloniex/pull/36/commits/97fa115611142c46c8dd51ee99f236e2891305d0) and see if it changes anything.

**Comment by kimkha** [comment]
Already apply that patch, but still same:

```Python 2.7.11 (default, Jan 22 2016, 08:29:18) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import poloniex
>>> polo = poloniex.Poloniex()
>>> polo.returnTicker()['BTC_ZEC']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "poloniex/__init__.py", line 233, in returnTicker
    return self.__call__('returnTicker')
  File "poloniex/__init__.py", line 222, in __call__
    return _loads(ret.text, parse_float=unicode)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

I think it based on my IP to request captcha page...

**Comment by kimkha** [comment]
I also sent ticket to Poloniex Support, and waiting the response...

**Comment by s4w3d0ff** [comment]
Ya, it does seem like your IP has been 'flagged'. It was most likely just 'blanketed' with others from your region (my guess is that polo has had issues in the past from there).

Hope they can resolve it quickly.

**Comment by kimkha** [comment]
I used Singapore IP, it's OK... 😢

**Comment by kimkha** [comment]
I got the reply from Poloniex Support team:

> Hi Kha,
>  
> Thank you for getting in touch.
> 
> I am afraid that this is a standard Cloudflare implementation - we have been trying to solve this on our end for a while now but so far have been unsuccessful.
> 
> I am very sorry for the inconvenience, we will continue to work on a solution to this problem and expect to have it working as expected again as soon as possible.
> 
> Best regards, 
> 
> Kevin
> Poloniex Support

It's issue of Poloniex side... Nothing to do here.

**Comment by laas29** [comment]
@kimkha try again executing your program in a US based hosting or server, it works for me but in node
